# syntax=docker/dockerfile:1.7
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir streamlit==1.39.0 plotly==5.24.1 pandas==2.2.3 \
    httpx==0.27.2 pyarrow==17.0.0

COPY dashboards/ ./dashboards/
COPY src/ ./src/
COPY configs/ ./configs/

EXPOSE 8501

CMD ["streamlit", "run", "dashboards/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
